version: 2
updates:
  # CLI updates
  - package-ecosystem: 'npm'
    directory: '/'
    commit-message:
      prefix: 'chore'
    labels:
      - '📦 dependencies'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'github-actions'
    directory: '/'
    commit-message:
      prefix: 'ci'
    schedule:
      interval: 'monthly'
    labels:
      - '📦 dependencies'
      - '🤖 ci/cd'
  # Template updates
  - package-ecosystem: 'npm'
    directories:
      - '/src/templates/**/*'
    commit-message:
      prefix: 'fix'
    labels:
      - '📦 dependencies'
    schedule:
      interval: 'monthly'
      day: 'monday'
